name: Build
run-name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          [
            "tanmatsu",
            "kami",
            "mch2022",
            "hackerhotel-2024",
            "esp32-p4-function-ev-board",
          ]
    steps:
      - run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Check out repository
        uses: actions/checkout@v4
      - run: make prepare
      - run: make build DEVICE=${{ matrix.device }} FAT=1
      - run: mv build/${{ matrix.device }}/bootloader/*.bin build/${{ matrix.device }}/
      - run: mv build/${{ matrix.device }}/bootloader/*.elf build/${{ matrix.device }}/
      - run: mv build/${{ matrix.device }}/partition_table/*.bin build/${{ matrix.device }}/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: |
            build/${{ matrix.device }}/*.bin
            build/${{ matrix.device }}/${{ matrix.device }}-launcher.elf
            build/${{ matrix.device }}/bootloader.bin
            build/${{ matrix.device }}/bootloader.elf
            build/${{ matrix.device }}/partition-table.bin
